### ISSUE TITLE
Trying for different sites

### ISSUE THREAD

**Issue by jcbrian** [0xhjohnson/captcha-harvester#2]
I change every instance of supreme as a url to the one i am targeting and same with sitekey. Than i run init and set the google account and the harvester opens at the supreme URL and sends the captcha to host "supremenewyork" when i check at /fetch

**Comment by 0xhjohnson** [comment]
Changing the sitekey and url worked fine for me. You can try it out from the commit referenced above.
```
# uninstall then proceed with installation below
git clone https://github.com/0xhjohnson/captcha-harvester.git
cd captcha-harvester
yarn install
yarn start # ctrl+c when finished
yarn add global ./
```

**Comment by jcbrian** [comment]
after following these instructions and re editing the file with palace site and site key im getting the same thing , the only thing i did different was use npm 

[![Screenshot from Gyazo](https://gyazo.com/5919ba688c91c0d7d7c9bec926ac69ec/raw)](https://gyazo.com/5919ba688c91c0d7d7c9bec926ac69ec)

[![Screenshot from Gyazo](https://gyazo.com/7825d13ff66a67a0452162be0b1b56c5/raw)](https://gyazo.com/7825d13ff66a67a0452162be0b1b56c5)

**Comment by 0xhjohnson** [comment]
Hmm rather than debugging this issue I’m going to add a feature where you can set the set the site for harvesting captchas. Seems like a better solution

**Comment by 0xhjohnson** [comment]
This is now fixed with the latest commits. The harvestcaptcha command takes in an optional command -s | --set which allows you to specify [url] and [sitekey]. If not specified will default to supreme.
```
# example command for palace
captcha-harvester hc --set https://shop-usa.palaceskateboards.com/ 6LeoeSkTAAAAAA9rkZs5oS82l69OEYjKRZAiKdaF
```
