### ISSUE TITLE
Login and one clicks

### ISSUE THREAD

**Issue by aarock1234** [0xhjohnson/captcha-harvester#9]
Login does not work anymore due to puppeteer detection. I have tried editing the code in many ways and it won't work.

I also noticed there are about 100% fade captchas, and no one clicks.

**Comment by 0xhjohnson** [comment]
One clicks have been a lot harder to get lately. Electron based harvesters seem to be the way to go. Here's an [electron based harvester](https://github.com/ItsFuego/Captcha-Solver) that should work better for now. I may rewrite this harvester in the future.

**Comment by NoahCardoza** [comment]
Sadly Google has even started blocking Electron (https://github.com/ItsFuego/Captcha-Solver/issues/3) but I did have some luck fudging the UA around but it didn't always work 100%.
